version: '3.7'

services:
  frontend:
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /tmp/build:/app/build
      # - ./frontend/build:/app/build
    depends_on:
      - backend
  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://postgres:mysecretpassword@db:5432/dream11
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: dream11
    ports:
      - "5433:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
